services:
  website:
    platform: linux/amd64
    image: ghcr.io/isaiah-harville/website/site:latest
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: website
    ports:
      - 3000:3000
