---
apiVersion: v1
kind: Service
metadata:
  name: website-anna
  labels:
    app: website-anna
    app.kubernetes.io/name: website-anna
    app.kubernetes.io/part-of: website
spec:
  selector:
    app: website-anna
  ports:
    - name: http
      port: 80
      targetPort: 3000
